import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./Providers"; // This already includes your ModalProvider

const seogefont = localFont({
  src: "./fonts/segoeuithis.ttf",
});

export const metadata: Metadata = {
  title: "India’s First AI-Powered Building Code Compliance Platform",
  description: "Generated by create next app",
};

import ClientLayout from "@/components/landing/ClientLayout";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${seogefont.className} antialiased`} suppressHydrationWarning>
        <Providers>
          <ClientLayout>
            {children}
          </ClientLayout>
        </Providers>
      </body>
    </html>
  );
}
